"""add milk, syrup, customizations

Revision ID: d2ca3902d0d1
Revises: 190b81d94e9c
Create Date: 2025-05-04 16:37:35.714366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ca3902d0d1'
down_revision = '190b81d94e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('review_id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('milk_option', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('syrup', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('customizations', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('customizations')
        batch_op.drop_column('syrup')
        batch_op.drop_column('milk_option')

    op.drop_table('reviews')
    # ### end Alembic commands ###
